### ISSUE TITLE
data-parsley-excluded form attribute is not working

### ISSUE THREAD

**Issue by vellotis** [guillaumepotier/Parsley.js#664]
data-parsley-excluded doesn't work when trying to set it explicitly for different forms.

(parsley.js 069a721fafd9a76388dca8023ea37043fb9dab07)
In Parsley init() function parsleyFormInstance.options paremeter is not taken into account  when creating new ParsleyOptionsFactory (ln:68). Therefor the parsley input options don't have correct selector for excluded elements (ln:76). ParsleyDefaults can be overriden only by setting ParsleyConfig globally or by setting the options when initializing Parsley on forms separately.

parsleyFormInstance.options should be taken into account when creating new ParsleyOptionsFactory.

**Comment by marcandre** [comment]
I believe this was fixed by #809 :smile:
Let me know if that's not the case...

**Comment by chrishough** [comment]
thank you @vellotis, I had to use this setup as well:
```js
window.ParsleyConfig = {
  errorsWrapper: '<li class="alert-box-item"></li>',
  errorTemplate: '<span></span>',
  excluded:
     // Defaults
    'input[type=button],' +
    'input[type=submit],' +
    'input[type=reset],'  +
    'input[type=hidden],' +
    '[disabled],'         +
    ':hidden,'            +
     // -- Additional attributes to look --
    '[data-parsley-disabled],' +  // Exclude specific input/select/radio/checkbox/etc
    '[data-parsley-disabled] *'   // Exclude all nesting inputs/selects/radios/checkboxes/etc
};
```
to make sure disabled fields i.e. 
```slim
          div[class="signin-remember-me"]
            = f.check_box(:remember_me, class: "large text-field", id: "signin-remember-me", "data-parsley-disabled" => "")
            label[for="signin-remember-me" class="signin-remember-me-label"]
```
were not validated.

**Comment by bnomei** [comment]
still broken. does not validate hidden fields even if options are set.

http://stackoverflow.com/questions/25162059/parsley-js-2-x-how-do-you-validate-hidden-fields/38122501#38122501

**Comment by marcandre** [comment]
@bnomel please provide an working example, for example starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101

**Comment by bnomei** [comment]
i am sorry. it works in a simple example. so it must be my error somewhere. maybe 200 forms on one page are not a good idea. ;-)

http://codepen.io/anon/pen/XKRyqG
